simulation_round1:
  description: >
    Conduct a first simulation round using a past Federal Reserve meeting event. Provide each agent with economic indicators and meeting conditions from January 2022.
    Each agent must vote on whether they would have increased or decreased the Federal Funds Target Rate by 25 or 50 bps under those conditions. 
    Their justifications must only reference the knowledge sources before Jan 2022. 
    They must compare the economic conditions at that time to similar historical events to support their decisions.
  expected_output: >
    A summary of each agent’s vote, reasoning, and historical comparisons during the simulation round. Include references to which historical examples and specific metrics were cited. 


reveal_and_learn1:
  description: >
    Reveal the actual result "maintain the rate" to all agents. 
    Instruct them to reflect on their initial decision and analyze why the Fed made its choice. 
    Each agent should briefly explain whether their original vote was correct or if they should have adjusted based on overlooked factors. 
    Emphasize that they should be more cautious and use all available knowledge sources to refine their upcoming votes.
  expected_output: >
    A short reflection from each agent explaining whether their simulation vote was accurate or if they miscalculated. If they miscalculated, they should consider to make a more precise prediction in the next round.

simulation_round2:
  description: >
    Conduct a second simulation round using a past Federal Reserve meeting event. Provide each agent with economic indicators and meeting conditions before February 2023.
    Each agent must vote on whether they would have increased or decreased the Federal Funds Target Rate by 25 or 50 bps under those conditions. 
    Their justifications must only reference the knowledge sources before February 2023. 
    Agents should compare the economic conditions at that time to similar historical events to support their decisions.
  expected_output: >
    A summary of each agent’s vote, reasoning, and historical comparisons during the simulation round. Include references to which historical examples and specific metrics were cited. 


reveal_and_learn2:
  description: >
    Reveal the actual result "increase by 25 bps" to all agents. 
    Instruct them to reflect on their initial decision and analyze why the Fed made its choice. 
    Each agent should briefly explain whether their original vote was correct or if they should have adjusted based on overlooked factors. 
    Emphasize that they should be more cautious and use all available knowledge sources to refine their upcoming votes.
  expected_output: >
    A short reflection from each agent explaining whether their simulation vote was accurate or if they miscalculated. This prepares them to make a more precise prediction in the next round.
